name: 'Run'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 250   
               
                uses: maxprilutskiy/change-report@v0
            with:
          destination: discord
          days: 7
          channel: '1289201997681004557'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
